### ISSUE TITLE
[Darrowshire] Redridge Mongrel drops Easter Dress outside without Noblegarden Event active

### ISSUE THREAD

**Issue by Keshi1** [LightsHope/server#104]
Date: 21/10/17
Realm: Darrowshire
Issue: The Redridge Mongrels in Redridge drop the Easter Dress item while the Noblegarden event is not active.
Dropped on: 21/10/17 on character Utherien at 1:31 PM GMT+2
Additional Notes: I'm not sure if that item is even supposed to drop at all, according to someone in the Discord it was supposed to only be obtained by opening Brightly Colored Eggs

**Comment by QAkvastskaft** [comment]
Easter dress should either not drop at all or it should be used instead of elegant dress id: 19028 in the eggs until patch 1.9-1.10

It only dropped from the noblegarden eggs during the 2005 event and later replaced in the loottables 

Sources:
https://web.archive.org/web/20060522145125/http://wow.allakhazam.com:80/db/object.html?wobject=423
https://web.archive.org/web/20071227210230/http://wow.allakhazam.com:80/db/item.html?witem=7809

For the 2006 event it got replaced by the elegant dress id: 19028 

Source:
https://web.archive.org/web/20071117083018/http://wow.allakhazam.com:80/db/object.html?wobject=499
Comments from 2006:
https://web.archive.org/web/20071124045907/http://wow.allakhazam.com:80/db/item.html?witem=19028
