### ISSUE TITLE
关于盗贼封印命运天赋的问题

### ISSUE THREAD

**Issue by ababdoned** [LightsHope/server#1084]
你好GM：
    我是L服一名盗贼玩家，我的盗贼在使用“封印命运”天赋的时候出现了一点问题，具体情况是在我参加工会活动的时候偶尔会出现这个天赋bug的情况，**在可以产生连击点的技能产生致命一击时，并不会获得额外的一个连击点**。这样的情况出现后，很影响我的角色伤害输出。一旦出现了这个bug，我只能靠离开团队然后关闭并重启客户端来尝试解决，有的时候bug不见了，有的时候不行。
这个bug根据我个人的使用经验来看，大约是每2个礼拜的团队活动会出现一次，最近一次出现是在上周三，也就是2017-12-20 22:00左右。
十分希望你们的团队能够尽快解决这个问题，非常感谢！PS：在测试服还可用的时候我也遇到了同样的情况。

**Comment by DarkmoonRabbit** [comment]
最好用英文。。。中文他们可能不受理……

**Comment by ababdoned** [comment]
很多名词不知道英文怎么说。。。

**Comment by Niceguyone** [comment]
Based on Google Translate, I think he/she is trying to say that the [Seal Fate](https://db.vanillagaming.org/?spell=14195) talent is sometimes working incorrectly by not giving additional combo points from critical strikes. Moreover, the bug can sometimes be fixed by leaving the raid and relaunching the client, and he/she has experienced it for two weeks and also on the PTR.

**Comment by ababdoned** [comment]
yes,that's what i mean,thks

**Comment by Niceguyone** [comment]
It seems that this bug has existed for quite a long time and you are not the only one with it.

See #613.

**Comment by ababdoned** [comment]
so where is the someone else?  GM do not know or can not fix it?

**Comment by Niceguyone** [comment]
No one seems to know exactly what is causing it. You can possibly help by describing the exact circumstances where it happens.
