### ISSUE TITLE
Elixir of Poison Resistance shouldn't have a 2 min CD

### ISSUE THREAD

**Issue by ohganot** [LightsHope/server#1098]
**Issue**
Elixir of Poison Resistance shares a 2 minute CD with potions.

**How it should be**
Elixir of Poison Resistance should be classified as an elixir and thus share the 3 second elixir usage cooldown with them.

**Proof**
https://web.archive.org/web/20060613195722/http://www.thottbot.com:80/?i=13343
http://web.archive.org/web/20060216180106/http://wow.allakhazam.com:80/item.html?witem=3386

Both databases list the Elixir as having a 3 second cooldown.

**Comment by Cabro** [comment]
Can confirm.

**Comment by Slicy** [comment]
That has been reported for ages with little to no care of getting it fixed even though it was sourced.

It actually got ninja changed just before AQ opened on Anathema to a 2 minutes CD based off the research of ONE QA member playing Horde side who found a retail video in which a rogue uses a consummable with a similar item icon and saw 2 mins CD poping off. The item being Jungle Remedy and not Poison Resistance Elixir, which he apparently had no knowledge of (interesting for a QA member right).

The reason it was kept at a 2 mins CD and was never fixed to how it should be is because of : 
- Lazy development despite it being an extremely easy fix (you'd assume it was changed so easily, the way around must be even easier since it was working fine in the first place),
- Poison Cleansing Totem was rendered useless by one single item,
- Consumable with the CD it should have was considered "too strong" by dev team,
- 0 fucks given to the usage of the item for pvp situations.

**Comment by ohganot** [comment]
Well, we have definite proof so it should be fixed before AQ40 launch hopefully.

**Comment by fgsfdss** [comment]
Elixir of Poison Resistance is an elixir. It got changed to be on potion cooldown when it was renamed to Potion of Curing in TBC.

**Comment by Omarthegreatone** [comment]
@Slicy its almost like when you proposed a fantasy cooldown on wcb, that got stuck on the server for ages.

**Comment by knasen88** [comment]
ayy yo HOL UP @Slicy , you be saying some irrelevant piece of shit info from some forum 15 years ago are NOT to be trusted? What about your WCB ""evidence"" you posted with such confidence.

you reap what you sow

**Comment by Cabro** [comment]
Man, even in the name, it says "elixir". It should be in elixir cooldown range.

**Comment by GuybrushGit** [comment]
There was never a question of what the cooldown should be, 3 seconds is correct.
The Elysium team just decided to keep it long since it killed any challenge the Viscidius encounter had.

**Comment by lequintal69** [comment]
They should disable it for AQ in my opinion. At least the first month

Also, this reminds me of the spell power scaling on zg sword/kazzak necklace debate. It was never intended to be abused, and probably never was ? (we couldnt find find a single video about spell power rogue abusing 43% spell power scaling to one shot everything). 

This is kinda the same here in my opinion. We couldnt find videos (or did we?) about ppl spamming the elixir in AQ, thus it was probably underused or not very well known. I cant see blizzard witnessing hundred of players abusing it on every gcd and not doing anything

I personnaly think they should get rid of it all alike. Just my 2c

**Comment by ohganot** [comment]
Most players still won't use it, because you would be required to use 15-20 of those each fight, if you didn't want to use poison dispels.

**Comment by ohganot** [comment]
The fix is already merged to the development branch.

**Comment by lequintal69** [comment]
players are way more tryhard. And pve aside, ppl will overabuse it in pvp as they did on nost
