### ISSUE TITLE
Someone else can loot your skinning results.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#1116]
If you skin a mob, but not loot the skin window, and close it, everyone else in your party/raid can steal it from you. I thought you should have the skinning results locked to you?

**Comment by Dalleren** [comment]
Well, party round-robin works like this. If you close the window anyone in the party can take your loot. Thinking or believing that it should work differently for e.g. skinning must carry proof. We can also start an endless discussion where evidence must shown that this is the current behavior. However applying common sense and advising not to close the loot window after skinning, the problem is more or less solved.

**Comment by Cabro** [comment]
Same with making items won on roll FFA so everyone can ninja them? w/e

**Comment by Dalleren** [comment]
Only if your bags are full :)

**Comment by Cabro** [comment]
Literally never happened on retail. In any patch. But whatever.

**Comment by ifyousayso** [comment]
Well, another thing is that after about 3 minutes of killing a mob, it should be lootable by ANYONE, including opposite faction. Of course, good luck finding proof of that.
