### ISSUE TITLE
Hurricane (Bow) missing 1-5 frost dmg. (Patch 1.8, LightsHope)

### ISSUE THREAD

**Issue by johnpettersson** [LightsHope/server#1145]
The epic lvl 48 bow Hurricane http://vanillawowdb.com/?item=2824 should do 1-5 frost dmg on each hit.

This might not technically be a server bug, instead its a bug from retail. (As it's mentioned in the Patch Notes from 1.11 that the frost damage did was previously broken and was then replaced by a frost dmg procc instead)

> Hurricane: This weapon was not dealing the listed frost damage. That listed frost damage has been replaced with a chance to trigger a damaging frost effect.
http://wowwiki.wikia.com/wiki/Patch_1.11.0

So i suppose if you strive to be as blizzlike as possible. dont fix it.
But if you strive to make things work as intended, please fix it.

**Comment by johnpettersson** [comment]
Hmm, maybe its impossible to fix. Since blizzard themselves couldnt :(

> Ranged Elemental Damage: Our ranged combat system does not allow a ranged weapon to do a mix of Elemental (Fire, Frost, Arcane, etc.) and Physical damage. Many ranged weapons existed which were listed as doing Elemental damage and did not function properly (the damage was dealt, but was treated as Physical). All of those weapons have been changed to deliver the Elemental damage as a chance on hit effect. Hurricane was previously changed this way in 1.11. The following ranged weapons are also fixed in 1.12: Bow of Searing Arrows, Dwarven Hand Cannon, Heartseeking Crossbow, Dark Iron Rifle, Galgann's Fireblaster, Quillshooter, Shell Launcher Shotgun, Venomstrike, and Verdant Keeper's Aim.
http://wowwiki.wikia.com/wiki/Patch_1.12.0

**Comment by brotalnia** [comment]
Nothing is missing, both versions exist in the db.
![bow](https://user-images.githubusercontent.com/6519171/34508271-23d8c848-f046-11e7-9944-2ef451f64aff.jpg)

**Comment by johnpettersson** [comment]
Try it out yourself then. It does'nt do any frostdmg.

**Comment by brotalnia** [comment]
There seems to be a general bug with ranged weapons, they do all the damage as physical. It is not specific to Hurricane, this item has the correct stats in the database. If ranged weapons didn't do the elemental damage on Blizzard's server too though, then things are working as intended, as we have successfully emulated that part of the combat system even down to the bugs. As this is an emulator, a 1 to 1 parallel of observed results is by definition considered perfection.

**Comment by johnpettersson** [comment]
That is 100% you guys being lazy.
Go ahead and make disgusting oozeling into the correct version aswell then if you want it to be 100% blizzlike. That thing completely broke the game in its 1.9 version. (you could spam it to become immune to other dots) Noone wants a truly blizzlike server.

**Comment by brotalnia** [comment]
> Noone wants a truly blizzlike server.

Speak for yourself. The point of every emulation project is to make things identical to how they worked on Blizzard's servers. I have never seen other projects like TrinityCore or MaNGOS tune encounters based on their preferences or commit any kinds of custom changes, and we should uphold the same standards here. Whether you personally like how specific things worked matters to nobody. If you explain to me the Disgusting Oozeling changes you are talking about i will implement them, provided it was not a spell related change.  (we don't do spell progression because it will require using the older clients to display the spells properly)

**Comment by brotalnia** [comment]
> I doubt you could fix it even if you wanted to

And since you taunted me, here you go. I made it so ranged elemental damage still goes through if the target is immune to physical.

https://streamable.com/882dy

But as you said yourself that is not blizzlike, ranged elemental damage never worked on Blizzard's servers, so it should not work here too.

**Comment by johnpettersson** [comment]
Sorry must've written that while in a particularly bad mood. I meant that it's a silly argument to say that we're so blizzlike that we even keep the same bugs that blizzard kept. You obviously don't. Go ahead and make c'thun tentacles spawn under the floor making the encounter impossible for weeks then for a true blizzlike experience. Noone wants that obviously.

And that was'nt meant as a taunt btw, kudos to you for fixing it though. I just tought that it was something that was'nt possible to fix since blizzard never fixed it, instead they just changed all those effects into random procs.

Sorry if i came of as an asshole. Keep up the good work!

**Comment by brotalnia** [comment]
> making the encounter impossible for weeks

I think there's quite a difference between something that was fixed within weeks, and something that never worked a certain way for the entirety of vanilla wow. The secondary elemental damage on ranged weapons never worked, that's why they removed the elemental damage and added a spell effects to those items in 1.11.
