### ISSUE TITLE
Now the database relationship is messy...

### ISSUE THREAD

**Issue by DarkmoonRabbit** [LightsHope/server#1267]
01. Is the current release  branch still using the old database? (World_full_09_november_2017.7z)
02. Will the future release  branches use the new database? (World_full_15_january_2018.7z)
03. Why not merge brotalnia / database? What is the reason?
04. Now the database relationship is messy...

**Comment by brotalnia** [comment]
Release branch still uses the 9 November database. Development branch uses the 15 January database. The database on the LH repo is partial because the spell data comes from the client and some people consider it a mortal sin. From now on download only from my repository. And stop using the release branch, that's only used on the lights hope live realms. All development work is done on the development branch and all issues should be tested there.
