### ISSUE TITLE
LBRS Vaelan

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#144]
Original report by:	Meiji1993

Vaelan in LBRS should appear as an orc raider at first crouching at the edge of the platform, then mind probe you and become vaelan.

Currently both NPCs are there and no script occurs

Source:
https://www.youtube.com/watch?v=FsE6iQ6XQTk

Comment by QAkvastskaft
Source with time stamp: https://youtu.be/FsE6iQ6XQTk?t=173

**Comment by GuybrushGit** [comment]
Spell used: http://www.wowhead.com/spell=16037/mind-probe

**Comment by brotalnia** [comment]
I wonder if blizzard used an areatrigger there that starts it or does he need to check for players in his script in MoveInLineOfSight. We could hack the spell to add a scripted effect and then script the event in `spell_scripts`, which would allow us to do everything without using scriptdev. And the spell getting casted on the player can be done in EventAI. We should probably just update `spell_scripts` to work with dummy effects too btw.

**Comment by brotalnia** [comment]
Synopsis of what needs to happen:
1. When player approaches him he casts spell 16037 and stands up at the same time.
2. A second later he changes entry and faces the player directly.
3. A second later he says text 1 (talk emote).
4. About 6-8 seconds later he says text 2 (talk emote) and gossip npc flag is added.

All of this can be done in the database scripting engine, provided we hack the spell to use scripted effect instead of dummy effect so it can be scripted in `spell_scripts`.

Another video of the event - https://www.youtube.com/watch?v=VVxOPiDVwNQ
