### ISSUE TITLE
Mob out of place for 1.7

### ISSUE THREAD

**Issue by QAkvastskaft** [LightsHope/server#153]
Original report by: dcish
Twilight Corrupter appearing near the moonwell in duskwood. This mob is part of the scepter quest chain introduced in 1.9.

http://db.vanillagaming.org/?npc=15625
http://wowwiki.wikia.com/wiki/Twilight_Corrupter

Comment by QAkvastskaft
NPC should be removed until 1.9

**Comment by Kochwurst** [comment]
Set SpawnFlags to 1 in Creature table for guid '1179144'. This will prevent him from spawning before 1.9 since the quest that triggers the areatrigger in Duskwood isn't available until 1.9. The areatrigger is handled in [.../script/easternkingdoms/duskwood.cpp](https://github.com/LightsHope/server/blob/development/src/scripts/eastern_kingdoms/duskwood/duskwood.cpp).
