### ISSUE TITLE
Bloodvine Drop Rate significantly reduced.

### ISSUE THREAD

**Issue by swatzlol** [LightsHope/server#188]
The herbs in Zul'Gurub have a chance at giving Bloodvine as they are herbed.

The drop rates appear to have been significantly reduced. I don't post this lightly, as I have used a large pool of testing myself.

300 runs or so before/after the noticeable difference.

Please look into this, thanks.

**Comment by Memnok1** [comment]
https://web.archive.org/web/20060812034237/http://www.thottbot.com:80/?i=51084

According to this, herbs should have between 10-15% chance to drop, since this is calculated with the amount of bloodvine that was actually harvested, since you can get up to 3 bloodvines from 1 herb that means the drop chance is probably closer to 9-10%.

I used the silversage for this example and judging from the other herbs you could make the assumption that the lower level herbs have the same drop rate but will drop a lower quantity of bloodvine. But again the sample size is probably not big enough for that.

It would be helpful if you posted your statistics to compare with the current droprate.

**Comment by Memnok1** [comment]
https://web.archive.org/web/20060812034237/http://www.thottbot.com:80/?i=51084

According to this, herbs should have between 10-15% chance to drop, since this is calculated with the amount of bloodvine that was actually harvested and you can get up to 3 bloodvines from 1 herb, that means the drop chance is probably closer to 9-10%.

I used the silversage for this example and judging from the other herbs you could make the assumption that the lower level herbs have the same drop rate but will drop a lower quantity of bloodvine. But again the sample size is probably not big enough for that.

It would be helpful if you posted your statistics to compare with the current droprate.

**Comment by swatzlol** [comment]
Thank you for your response.

As I don’t have recorded statistics, at the moment...I can give my estimate of what I had completed before/after what I feel was the change.

I started farming ZG a day after release. I hit 6 herb nodes per run. I farmed around 10 hours a day. I average about 26-30 herb nodes per hour. 15% would be averaging 3.9-4.5 bloodvine procs per hour.

I would average 2 bloodline ‘procs’ per run. This is the proc itself off the herb, not counting x2 or x3 proc. Some runs I would walk away with 11 bloodvine per run. Over the entire duration that ZG had been out, I had never gone 2 runs in a row without a single bloodvine. I would also have multiple x2’s and x3’s per hour.

It’s been roughly 48 hours since I noticed the change. Now I’ve farmed about 10 hours total over the past 48 hours. In these 10 hours alone, I had One x2 and One x3. I’ve gone multiple runs without a single bloodvine. 

In 3 hours farming yesterday, I actually got more Arcane Crystals from the 2 nodes in ZG each run than I did bloodvine from the 6 herb nodes. Granted 3 hours isn’t all that large of a data pool.

I will be farming it again after work tonight, for about 5 hours. I can provide a more accurate statistic then.

This wasn’t not a side affect of the world herbalism hot fix, as the bloodvine was still good farming after that.

**Comment by GuybrushGit** [comment]
Loot chance is set at 15% in the db.

**Comment by swatzlol** [comment]
Can you see a past mirror of the live database? Let’s say 3-4 days ago? Perhaps it’s good now, and was incorrectly higher chance before. 

Without having 100+ hours farming it yet, I am fairly certain it is different rates than it was 3-4 days ago. Even the x2 and x3 procs have depreciated. 

I will be doing some more testing myself. I understand what RNG is, and I don’t bring this up lightly. I’m a grinder, I like spending long periods of time doing something. I notice the difference over long periods, not just a few runs.
