### ISSUE TITLE
Can't Stealth or Vanish on my Rogue 

### ISSUE THREAD

**Issue by Tubeless** [LightsHope/server#279]
Hey team, at the moment I'm a bit of a warrior rogue, as fun as it is I'd like to be able to rogue again properly. 

When I try and use stealth or vanish I get the error "You can't do that yet" its only just started yesterday and hasn't gone away since.

The first time it happened I was leveling up my lock picking in the barrens in the tower where rogues complete the poison quest.

**Comment by Tubeless** [comment]
so it turns out the debuff that chest gives you stop you from going stealth - shammy or druid can fix that issue

**Comment by GuybrushGit** [comment]
Never happened again?

**Comment by brotalnia** [comment]
@GuybrushGit He had the Touch of Zanzil debuff, it's not a bug. Well technically it is, but the current implementation is intentional.

http://db.vanillagaming.org/?spell=9991

Currently Touch of Zanzil is hacked in the db to work like it does in TBC/WotLK, meaning it prevents you from entering stealth. In vanilla it is supposed to reduce your stealth level instead, so that everyone can still see you from the same distance while stealthed, effectively rendering stealth useless. However that does not currently work in the core, as any spell with stealth level modifying effect is handled as if it applies stealth. That leads to the buff not being applied to the player at all, because you get afflicted by it while looting the chest, and you can't be stealthed while looting. If you were to add it to yourself with a command, it is removed whenever you use any ability, loot anything, attack something, basically everything that removes stealth. So i hacked it to work like it does in later versions, cause at least it works this way.
