### ISSUE TITLE
Drakkisath's Conflagration does double ticks.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#334]
You get 2x ticks at once, instead of 1x tick/second.
I've seen this happen on basically every private server.

http://db.vanillagaming.org/?spell=16806 - i THINK this is the spell for Drakkisath, shouldn't this NOT damage you, only the others? You already take damage from http://db.vanillagaming.org/?spell=16805

Once the boss dies, you stop getting 2x ticks, you only get 1x tick. Something is really off.

Also check the Razorgore's Conflagration please, as I honestly cannot on live servers.

**Comment by berillis** [comment]
Happens on both bosses' (Razorgore and Drakkisath) Conflagrations. The conflagration hits you first and then the aoe effect hits you for the second damage, dealing the damage twice, when it only should do it once. Usually the damage is dealt to the tank and this is not a problem, but can cause issues for players with bad gear.

**Comment by Cabro** [comment]
@GuybrushGit can you confirm that you should take 2xticks at once?

**Comment by GuybrushGit** [comment]
I couldn't reproduce it. Conflagration only does one 300 damage tick per second in dev.

**Comment by Cabro** [comment]
Why is this closed?

**Comment by Tobschinski** [comment]
It looks incorrect to me.

Let me remind you: The combat log in general does not list every single spellcast, it is also fully customizable.

If you look at the combat-text (I think it is MSCT) you can see a lot more than just 10 ticks. The quality of the video is bad, but you will notice it no matter what.
Also check the combat-logs' wording, it says YOUR conflagration hits you for ...
This should be spell 16806, because the conflagrated player is the one casting it. Spell 23023 is cast by Razorgore.

To show the difference between the default and MS combat-text, check [this](https://youtu.be/K48ZEHk5FAQ?t=22). You see 10 numbers (or absorbs) in yellow writing, but a lot more in purple.

The druid, despite being buffed with hots and even a fireshield, loses more than [4.000 health]((https://youtu.be/K48ZEHk5FAQ?t=33)) from one conflagration. 10 ticks with a maximum of 300 damage each tick would not be able to do that.
