### ISSUE TITLE
Persistent hunter bug

### ISSUE THREAD

**Issue by Sesimie1042** [LightsHope/server#363]
Hello, I play a night elf hunter, and cant seem to gain Loyalty levels nor training points for any of my pets. I was told to post here if the problem wasnt solved upon deleting my WTF folder. It's not working.
 Character name is
'Gluden'  on the Elysium server.

**Comment by lovemonkeyz** [comment]
What level are you? Have you finished ALL the level 10 hunter quests? Have you actually tamed a new pet instead of having the last one tamed from Taming Rod? 

There's been a bunch of people who tend to miss a few tiny details on how to gain pet loyalty/training points (you gain TP from loyalty). How long have you had your pet? How long have you been feeding it? Do you keep it at max happiness at all times?

**Comment by Sesimie1042** [comment]
Hello. I was level 18 at the time, I chose to delete my character, purely out of frustration, and make a new one. I'm currently level 12 with the same issue. I keep my pet happy at all times, I've done all the quests, I've tamed an owl (Not the one from the taming quest) and a wolf on my old character... I've even re-downloaded my client a few times, but to no avail.


________________________________
Fra: lovemonkeyz <notifications@github.com>
Sendt: 29. oktober 2017 11:21
Til: LightsHope/server
Cc: Sesimie1042; Author
Emne: Re: [LightsHope/server] Persistent hunter bug (#363)


What level are you? Have you finished ALL the level 10 hunter quests? Have you actually tamed a new pet instead of having the last one tamed from Taming Rod?

There's been a bunch of people who tend to miss a few tiny details on how to gain pet loyalty/training points (you gain TP from loyalty). How long have you had your pet? How long have you been feeding it? Do you keep it at max happiness at all times?

**Comment by QAkvastskaft** [comment]
Is this still an issue?
