### ISSUE TITLE
Melee range for attacks is too short.

### ISSUE THREAD

**Issue by Cabro** [LightsHope/server#389]
I was checking old videos from vanilla and it hit me. Melee attacks on the server go off if you are really close to your target.

But check this video and the range from which he attacks.
https://youtu.be/5MAZkK_xdFg?t=3m54s

**Comment by ohganot** [comment]
This is called the melee leeway mechanic.

Basically it addes 2.5 yards to your melee attack range while you're running to make PvP more smooth and reliable for melee players.

Here is the bug-report from Kronos with detailed evidence and discussion: https://vanilla-twinhead.twinstar.cz/?issue=8237

I'm not sure if leeway mechanic works on Light's Hope, but that would most likely be the problem if there is one.

**Comment by vindruvor** [comment]
iirc they tried to add this ages ago to this server, idk if it worked though

**Comment by Cabro** [comment]
This should be fixed, as it makes PvP for melees really bad, if you ask me.

**Comment by Fiskehatt** [comment]
They made some changes on Elysium a few months ago:

https://github.com/elysium-project/server/pull/12

https://forum.elysium-project.org/topic/43686-development-update-05042017/

>  Improvements to the melee leeway mechanics have been made 

I haven't tested the leeway mechanic personally but maybe the low range is just caused by server lag? Anyways, they should look into as it can be kinda gamebreaking for melee. 

P.S. Here is a fun video on how bad it was on Emerald Dream :)

https://www.youtube.com/watch?v=0CsS4wLCWpI

**Comment by supasteed** [comment]
Yes please fix this. I support cabro 100%

**Comment by GuybrushGit** [comment]
The melee leeway mechanic is implemented.

**Comment by Cabro** [comment]
Ok then.
