### ISSUE TITLE
Rogues can't use Invisibility Potion of any sort.

### ISSUE THREAD

**Issue by tyrachnydia** [LightsHope/server#547]
Hi, 

We've tested this multiple times, Rogues can't seem to use any Invisibility potions. The energy tick they have refreshing their energy bar is taking them out of stealth making them visable for aggressive mobs.

Below you can see a rogue trying it on Darrowshire. It also includes the reaction of the rogue on discord.

"rogues are fucked, just tested it on a lvl 10 aggressive mob in front of org, he didnt target me the moment i was in there so it was likely the energy tick"

https://media.discordapp.net/attachments/263812463252865025/377955854273609740/invis.png

I'm not a Github pro so I hope I reported this issue properly if there is anything I can do to improve this bug post please inform me.

**Comment by martinjlowm** [comment]
Fear not: https://github.com/LightsHope/server/commit/6d5b30847824c13928d029688ac86f17c5b45704

**Comment by tyrachnydia** [comment]
Very possible, i'm just 100% sure something rogue related is causing it to bug. We thought it was the energy ticking. Could you explain why you think its Detect Traps ?

**Comment by Nyatsuelysium** [comment]
Can confirm on Elysium as well, I just tried it on a lvl 51 ooze in felwood, before combat, i popped lesser invis potion, then waited 2 seconds, and walked up to the mob and he attacked me instantly without me doing anything else but just walking normally.

**Comment by martinjlowm** [comment]
@tyrachnydia 

The problem is https://github.com/LightsHope/server/commit/6d5b30847824c13928d029688ac86f17c5b45704?diff=unified#diff-98bbab6de99186d6bf6262ae0af758bcL7630

The logic on the highlighted line would result in creatures detecting rogues with invisibility if they know the Detect Traps ability. The `canDetectInvisibilityOf`-method was invoked as both `creature -> player` and `player -> creature`, which was originally meant for Mages' Invisibility spell in TBC. In the situation where rogues know the Detect Traps ability, `(player) canDetectInvisibilityOf (creature)` would return true from the first conditional check. The `invisible` variable would then incorrectly be set to `false`, hence why creatures would detect rogues, because they weren't evaluated as being invisible.

**Comment by tyrachnydia** [comment]
@martinjlowm Yea, this makes sense. Great working finding :o 👍 

But This isn't supposed to be like the case for vanilla though? As I stated before I can read some code and the logic behind it but I'm no github 'hero' is this changed now or fixable?
