### ISSUE TITLE
 "Skull of Impending Doom" is gone

### ISSUE THREAD

**Issue by eska123** [LightsHope/server#607]
Hello GM.
I play on server Lights hope, my character name is "Bgstar"
 item "Skull of Impending Doom" is gone form my char
LINK TO ITEM> http://db.vanillagaming.org/?item=4984
  I have not idea when and how. This item is really powerfull on BG, especially for druid.
I dont see reason to play druid pvp without that item.
I recived it from the quest chain, not able to do once again.
I really would to recovery this item.

**Comment by Sabre142** [comment]
Make a ticket.

**Comment by eska123** [comment]
![lhbug](https://user-images.githubusercontent.com/33609780/32704963-b9f713c0-c7d3-11e7-9c72-183c8e939388.png)

**Comment by GuybrushGit** [comment]
You probably vendored it by accident.

**Comment by eska123** [comment]
Oh ! No, I pay attention for selling stuff. Items what I need always hold on last backpack ( last row, as in picture)

**Comment by QAkvastskaft** [comment]
For some cases we provide item refunds. Please see if you meet the requirements here: 

[terms-of-use-rules-regulations](https://forum.lightshope.org/viewtopic.php?f=4&p=13119#p13119) section III for information.

Then if you meet the requirements make an ingame ticket to a GM for a request.

Press  “Help request” → “Issues that GMs can assist with” → “Stuck” → “Still not working, Page a GM” to bring up the GM ticket system. Write your issue here and a GM will assist you as soon as possible.

Thank you
