### ISSUE TITLE
Missing database and migration files

### ISSUE THREAD

**Issue by SpaceVector** [LightsHope/server#621]
Currently, using a freshly compiled core and newly made database makes the core crash because of an invalid SQL statement. This comes from a merged PR made by @brotalnia https://github.com/LightsHope/server/pull/524 since there are lots of migration files missing, like this one https://github.com/LightsHope/server/pull/524/commits/da312662841e711a2796247dc1ace18d0242a1ac which is supposed to make the new table broadcast_text, whose absence currently crashes the core at startup.

Also, this repository doesn't provide any full DB and you currently need to go to Elysium's project repo to get the latest. Could it be added please ?

**Comment by dimefox** [comment]
Looks like there is a full world in the [Releases](https://github.com/LightsHope/server/releases/tag/1.1.9) now. It took me a while to find this too.

**Comment by brotalnia** [comment]
The full db is under releases now to avoid inflating the repo. The broadcast text migration was not included in the commit on purpose because it was too big, and at least for me MySQL freezes when you try to create a 70 mb procedure (all migrations are added via procedure now). Instead i just made a new db release with the table already there.
