### ISSUE TITLE
Quest ID 474 'Defeat Nek'rosh' Unobtainable

### ISSUE THREAD

**Issue by DRPou** [LightsHope/server#731]
Was questing in wetlands, and after completing Nek'roshs gambit: 

https://web.archive.org/web/20060321222113/http://wow.allakhazam.com:80/db/quest.html?wquest=465

A screen popped up, for a new quest, the final quest in the series, "Defeat Nek'rosh". Naturally, I click accept and be on my way. Why wouldn't I accept a quest while levelling?

Quest found here: 

https://web.archive.org/web/20051126022216/http://wow.allakhazam.com:80/db/quest.html?wquest=474

I soon realised that I didn't even have the quest in my quest log. I can't think of any reason as to why I wouldn't have. my quest log isn't full and wasn't full at the time (Otherwise I would've been prompted It was full and the quest text wouldn't have disappeared upon clicking accept).

To get this quest, you must be interacting with a catapult that you burned in the previous quest. However, one completing the previous quest, the catapult becomes non-interactive and you can't obtain this quest anywhere!

Really sucks when you can't get a quest, even when you clicked accept on it, yet it bugged out.

Things I have tried (After contacting a GM, who recommended these solutions, I have in game mail copies):

Deleting WDB and WTF folders and disabling all addons

On top of these
Relogging
Reinstalling
Reloading

I don't know what else to do, and I'm afraid that its not possible to attain the quest anymore.
![screenshot1](https://user-images.githubusercontent.com/29979098/33071040-f1c43316-ceb1-11e7-9764-ebc2077b7b68.jpg)

**Comment by QAkvastskaft** [comment]
Comment to OP:
Currently the follow up http://vanillawowdb.com/?quest=474 require level 26 while 
http://vanillawowdb.com/?quest=465 require level 25 so that is likely the issue. 
Try to get the quest at level 26 and see if it works then.

Correct behavior:
Quest id 474 and 465 should be min lvl 23

Source:
![image](https://user-images.githubusercontent.com/26366996/33090814-8fbd7936-cef5-11e7-8646-5c4e3016fb4d.png)
