### ISSUE TITLE
Hunter T2 stats are fucked

### ISSUE THREAD

**Issue by pateuvasiliu** [LightsHope/server#768]
The legs should have 1% crit 1% hit, they have 2% hit now

The shoulders should have 1% hit, they have 0% hit now

**Comment by QAkvastskaft** [comment]
Item stats gets updated with patches. If you have any sources for the new stats being incorrect please provide them.

**Comment by Kolmarwow** [comment]
https://web.archive.org/web/20051226125927/http://wow.allakhazam.com:80/db/itemset.html?setid=215

That's a link to how the dragonstalker set should be as of patch 1.8, assuming this issue is for Lightbringer. The legs & shoulders are correct and QAkvastskaft is completely right, they will be updated to the stats that Pateuvasiliu is thinking of in patch 1.9 (which should arrive in January 2018).
