### ISSUE TITLE
[Lightbringer] Doc Mixilpixil

### ISSUE THREAD

**Issue by Totier** [LightsHope/server#818]
The creature Doc Mixilpixil in Stormwind appears to have broken. See attached video. A GM reset (.die) did not solve the issue.

http://youtu.be/r9esmXMf61k?hd=1

**Comment by brotalnia** [comment]
The script for this npc is different on dev branch, i redid it properly with blizzlike texts, so most likely this issue wont happen anymore once release catches up to development.

**Comment by QAkvastskaft** [comment]
Which fix was it so I know when to close it?

**Comment by brotalnia** [comment]
It was in the migration that added broadcasts texts, since i had to go through all `db_script_string` entries and replace them with broadcast texts ids wherever they were used. I fixed any issues with scripts that used those texts as i was doing that, and a quest script involving this NPC was one of them. That migration was not included in the repo as it was 70 mb in size, and i made a new db release with it included instead. So whenever the broadcast text implementation goes live, the fix involving Doc Mixilpixil would be live as well.
