### ISSUE TITLE
Lunar Healing Wand +35 should not exist on Lightbringer

### ISSUE THREAD

**Issue by floplol** [LightsHope/server#822]
Blizzard nerfed the +damage and +healing values on these items but  a +35 wand dropped today and needs to be removed from the game. All future wands should drop in nerfed state and old items should not be reverted back.

Proof of item existing -https://cdn.discordapp.com/attachments/318146701154058240/384791136482492428/unknown.png

Patch Notes https://www.graffes.com/forums/showthread.php?37921-green-wands-stealth-nerfed
Incorrect amounts of abilities such as Attack Power, Increased Fire Damage, or Increased Healing Damage were being applied to all random item property world drops. Two handed weapons such as Staves had much lower amounts of these abilities, while ranged and one handed weapons had too much. All further drops of these items will have the correct amounts, but previously dropped items will not be affected by this change.

More evidence

August 2005  pre nerf https://web.archive.org/web/20050829052852/http://wow.allakhazam.com:80/db/item.html?witem=15281

February 2006 nerfed
https://web.archive.org/web/20060216103712/http://wow.allakhazam.com:80/db/item.html?witem=15281

**Comment by GuybrushGit** [comment]
Those patch notes are from 1.9. Lightbringer is on patch 1.8.
Also Blizzard did not destroy the wands that already had dropped, the players kept them.

**Comment by floplol** [comment]
Hence the comment “old items should not be reverted back”. 

There were no 23 or 35 wands on the server until the last patch was released unlike in actual Vanilla. Unless it’s believable that they didn’t drop any on the server for 10 months and now there are multiple in the first week? And now they will only be attainable for 1.5 months before 1.9 is released? Why stealth add them at all?

**Comment by thepparker** [comment]
They weren't stealth added. In fact, you can clearly read in the patch notes that they were introduced last maintenance. Just because they were not available previously does not mean we should ignore that they are in fact meant to be available. Regardless of how long they are attainable, it is a step in achieving correct itemization.

The shorter period than intended is unfortunate, but it will give players something to aim for in the wait for 1.9 and reward people with somewhat prized possessions.
