### ISSUE TITLE
Felstriker does not proc correctly

### ISSUE THREAD

**Issue by Lythria** [LightsHope/server#851]
Felstriker (ID: 12590) is a dagger with the following tooltip: "Chance on hit: All attacks are guaranteed to land and will be critical strikes for the next 3 sec."

However, this is incorrect. While under influence of the proc, the player can still have their attacks dodged, parried and blocked. The proc turns misses into hits and all hits into crits, but does nothing with block/parry/dodge. One could argue that parries and blocks are "landed" attacks, but an attack that has been dodged has not landed on anything. Felstriker's proc should therefore disregard dodge and make all attacks successful as the tooltip denotes, otherwise the "guarantee" is a false claim.

The attached pictures below shows instances of dodging, parrying and blocks while the proc is active.

![fel proc](https://user-images.githubusercontent.com/28778657/33393169-8c7be0d8-d53e-11e7-853c-d50625db509f.png)

![blockstriker](https://user-images.githubusercontent.com/28778657/33393962-2298f266-d541-11e7-8aaf-62110810f5a3.png)

**Comment by GuybrushGit** [comment]
Some observations:

- The felstriker spell only has aura 54 SPELL_AURA_MOD_HIT_CHANCE, nothing related to parry or dodge. There actually isn't any aura type to modify target dodge or parry in the game.
- One comment says: `However there is still a chance for the enemy to block/dodge/parry.``
- And then another comment says: `That means...you will not miss, they cannot parry, dodge, or block... `
  but then he says `I know this because my friend has the dagger,` so he doesn't even have the dagger...
>http://web.archive.org/web/20061217092710/http://www.thottbot.com:80/?i=20470
