### ISSUE TITLE
Lightshope - Lightbringer PvP - Dont get Ony/Nef World Buff while in Maincitys.

### ISSUE THREAD

**Issue by Milberahmen1** [LightsHope/server#895]
Hello everyone,

I dont Get the Nef/Ony World-Buff while i´m in the maincitys, Lightbringer PvP Gamemasters said i should delete the WTF WDB folder. But nothing happend... Then they said i should post the Porblem in this forum...

Can please anyone Help me?

**Comment by GuybrushGit** [comment]
Are you friendly with Orgrimmar / Stormwind?

**Comment by Milberahmen1** [comment]
no, you think thats the problem?

**Comment by GuybrushGit** [comment]
Yes

**Comment by Milberahmen1** [comment]
does i need ogrimmar or darkspear reputation to get the buff while in ogrimmar?

**Comment by Cabro** [comment]
Apparently you need.

**Comment by Papa2Cherries** [comment]
Ok so this should not be closed.  everyone starts with 100 into friendly, i just made a new toon and confirmed this, so faction rep should not matter, even if it does, i am reveared with SW so that is not the case.  I was in stormwind when the buff happened and i did not receive it, nor did half the guards, of the same name type.  So it seems that it is a bug that is not hitting everyone and should be fixed as such.  I then an hour later received the buff standing in a different location of stormwind having not done anything else rep/quest/xp wise.
