### ISSUE TITLE
Custom change: King Gordok in DM North

### ISSUE THREAD

**Issue by Zarant** [LightsHope/server#917]
King Gordok teleports his current target next to him. making it next to impossible to solo.
I'm fully aware that it was changed to stop hunters from farming the tribute chest. I do think that tribute farming should be more difficult, more time consuming and award less gold per hour in general, but just making the King impossible to solo is an extreme measure, soloing instances is a defining trait of the hunter class,

Source:
http://www.warcraftmovies.com/movieview.php?id=27092
https://youtu.be/dXE_RR5XzE8?t=11m15s

**Comment by brotalnia** [comment]
The custom scum has been obliterated. May the blizzlike be with you.
https://github.com/LightsHope/server/commit/69e41ec0e40a88d70d3dd501f132b6891c628f64

**Comment by Manlet** [comment]
There's a very good reason for the teleport to be in. The economy would get fucked if hunters could print 150g+ an hour in an instance.

**Comment by brotalnia** [comment]
Q: What is the purpose of this software?
A: To emulate Blizzard's vanilla servers as they were then.

Q: Did this behavior exist on the retail vanilla servers?
A: No. It is completely fictional, made up by people who are not affiliated with Blizzard.

Conclusion: Incorrect behavior is to be corrected.

Whether you like the way it worked or not is completely irrelevant, the main repository for an **EMULATOR** should not contain code that produces behavior which deviates from the thing we are emulating. Such code is faulty and is to be corrected to match the behavior observed on Blizzard's servers. All custom features must be optional and off by default.

**Comment by Manlet** [comment]
The 'people who are not affiliated with Blizzard' are the staff who did this keep the server economy in better shape.

**This is not a 100% Blizzlike server and never will be.**

Having herbs be on dynamic respawn, with multiple black lotus per hour, is not blizzlike but its necessary for a server of this size. Likewise with hunter bow quest demons respawning faster and not having such a big despawn time penalty. With the knowledge we all have about vanilla today, certain aspects of the game have to be changed for a healthy server. This is one of them.

**Comment by Zarant** [comment]
The only major impact on the server economy would stem from the surplus of mana pots and enchanting mats. DM tribute gold is just a drop in a bucket compared to everything else that is going on. The only thing that would be affected by this change is the price of the aforementioned items.

**Comment by Manlet** [comment]
> DM tribute gold is just a drop in a bucket compared to everything else that is going on.

You're joking right? Hunter's can farm 150g+ an hour, inside an instance, solo. You can even vendor all the loot inside the instance too. It's incredibly overpowered, every other instance farming method is a 'drop in a bucket'

> The only thing that would be affected by this change is the price of the aforementioned items.

Have you played on a server recently where solo tribute farming is allowed? The price of almost everything becomes inflated because people can print gold easily and safely. Everyone gets hunter alts and does the same stuff to keep up.

**Comment by Zarant** [comment]
I'm speaking from experience, I played on K1 and K2 after the nost shutdown, they had things like solo tribute farm and dm east lasher farm enabled from day 1, in a server that people could actually buy level 60 hunters and mages. The only major difference I noticed from the old nost server was the price of mana pots and enchanting mats, they were cheap af. Hell you can even log on kronos right now and compare their AH to the Anathema AH, since both have similar population and are on the same patch. The day to day stuff you buy on both servers have very similar prices.

**Comment by brotalnia** [comment]
Do you see TrinityCore rebalancing the game? Does cMaNGOS add custom abilities to bosses to make them harder? No they do not, and if you tried pushing such crap to their repo you'd be denied immediately and shunned away. This is an open-source emulator for vanilla wow, and as such the code provided on the repository should be one that reflects that. You are free to make any modifications to the code base on your own fork, but the MAIN REPO should be clean and not contain forced unblizzlike changes. The "it will never be 100% perfect so lets not even try" argument is nonsensical, nothing in this world is perfect, does that mean we shouldn't strive to make things better? If people followed your logic nothing would ever be fixed, since inevitably flaws would still exist, and as such the whole endeavor is futile.

**Comment by Manlet** [comment]
> I'm speaking from experience, I played on K1 and K2 after the nost shutdown

Did you play with your eyes closed? I too played those servers, and the effect of solo tributes on the economy was easily noticeable. When it got popular/known with the masses, consume prices close to doubled, specific hunter consumes like mongoose near tripled. Most people I know either got a hunter alt or shared one, no reason not to when such an overpowered farming method was legal.

> Do you see TrinityCore rebalancing the game? Does cMaNGOS add custom abilities to bosses to make them harder?

No idea, I don't visit those repos, this is the Lights Hope github.

> The "it will never be 100% perfect so lets not even try" argument is nonsensical, nothing in this world is perfect, does that mean we shouldn't strive to make things better?

Can you tell me where I said this? I only mentioned that this will never be 100% blizzlike, and for good reason. For sure we should try to strive to make this project better, that's what I'm doing by making sure solo hunter tribute farming stays nerfed ;)

**Comment by staplerx300** [comment]
> Most people I know either got a hunter alt or shared one, no reason not to when such an overpowered farming method was legal.

People do this now on lights hope/elysium but with mages.

**Comment by Manlet** [comment]
> People do this now on lights hope/elysium but with mages.

Big difference between 30-40g an hour as mage, and 150g an hour as hunter

**Comment by bigfgeg** [comment]
Mages can already farm better than every other class. 

Why exactly are hunters not allowed to farm better than every other class? Where do you draw this arbitrary line?

**Comment by Manlet** [comment]
>Why exactly are hunters not allowed to farm better than every other class? Where do you draw this arbitrary line?

When the amount capable of farming vastly exceeds all other instance based methods.

Mages can get a constant 30-40g per hour, 
Warriors and healers can 2man farm DM E for 40-50g each per hour. 
Hunters and Warlocks can solo farm Mara for 30-40g per hour.
**Hunters can solo tribute for 150g+ per hour.** See how out of place this is?

>Also, it's not gamebreakingly much. With certain gathering professions and the proper know-how, you can already make like 100-200g an hour, depending on luck.

We are talking about instance based farming methods. If one person is getting 100-200g per hour by farming black lotus for example, it means this lotus resource is unable to be farmed by other people at the time. The scarcity of the world farm resource keeps it in check, because not everyone can farm that same thing at the same time.

Instance farming on the other hand, is mass repeatable, able to be farmed 24/7, regardless of faction presence in the zone or population. You can farm it in complete safety, and there is no one that can contest it, like there would be with resource farming in the world. This is why it is so broken to have powerful instance farming available.

>I mean, people on retail did this and it didn't ruin any servers economy. I dont understand the issue here.

It was extremely rare on retail, the general public knowledge of it back then is much less than it is now. Now everyone can watch a youtube video guide and get 11min or below solo trib runs after a few hours of practice.

**Comment by bigfgeg** [comment]
>>Warriors and healers can 2man farm DM E for 40-50g each per hour.

No, it's 15-20g each per hour depending on arcane crystal luck.

>>Hunters and Warlocks can solo farm Mara for 30-40g per hour.

No, it's again about 15-25g per hour depending on luck. 

Suddenly it's the constantly 30-40g per hour that mages can make that seems out of place. Wonder why you would want to misrepresent that heavily?

>>Manlet

Hmmmm...

**Comment by Manlet** [comment]
You think I'm misrepresenting the amount warriors make from jump runs because my main is a mage? Surely if you're willing to personally attack me like that, you realise I have a warrior too right? 

> > Warriors and healers can 2man farm DM E for 40-50g each per hour.
>No, it's 15-20g each per hour depending on arcane crystal luck.

The final boss of DM E drops 2x Blues, these are both sharded into 2x Large Brilliant Shards.
Large Brilliant Shards are currently selling for 4-5G each.
5x Runs in 1hr, the final boss alone will give the warrior and healer 5x Large Brilliant Shards each = 20-25G each/hr from just one of the 3 bosses.

20-25G each person, **from only half of the run**, and it's already higher than your estimate. I didn't even include the amount gained from the thorium veins, the extra shards from the two bosses before him or the felcloth from the satyrs. I'm really struggling to figure out how exactly you came up with such a misinformed estimate.
Please don't comment on changes unless you play and actually understand the game and mechanics we are discussing.

**Comment by Zarant** [comment]
I farmed the living shit out of DM:N on kronos, shards were selling for 3.5g each and mana pots 1.5g each. I got about 25g/run on average but half of this gold was from selling potions, enchanting mats and class books. Farming lashers in dm east or doing the BRD aoe grind, generate about the same raw GPH. The claim that it ruins the economy and inflate the prices is completely false, Kronos always had stable prices, and the reason plaguebloom went for 50g and all other herbs didn't had something to do with their herb respawn rates, on this server plaguebloom is all over the place, you can easily farm 2 to 3 stacks/hour.
Allowing hunters to farm DM north will just make caster consumables in general cheaper, it will flood the market with shards and mana potions and will end up reducing the demand for dreamfoil and icecap.

Anyway, that is not the main issue, I don't think it's our place to judge if this is balanced or not, vanilla had many quirks, and soloing 5 man dungeons, either for money, pre-raid gear or just for bragging rights was a defining trait of the hunter class, and by just outright denying hunters to do it, you are taking away a big aspect of the hunter class.

When asked about this on the crestfall forums they had a much more elegant way to tackle this issue:

> Our plans for this currently extend no further than fixing the bug that allows players on private servers to reset an instance from inside the instance, and to make the Gordok Tribute chest unobtainable unless Guard Slip'kik and Captain Kromcrush are dealt with in some way - either by frost trap, ogre suit, or killing them in combat.  Alternatively, we can set a script condition such that unless Slip'kik is frozen, he is considered "dead", and unless Kromcrush preforms his Ogre Suit routine, he is also considered "dead" for the purposes of generating Tribute loot. 

http://forums.crestfall-gaming.com/index.php?/topic/1812-ways-of-gold-farming-banned-from-crestfall/&do=findComment&comment=26135

**Comment by Manlet** [comment]
>Farming lashers in dm east or doing the BRD aoe grind, generate about the same raw GPH

_Farming lashers generates the same raw gold per hour as solo tribute farming_

Alright I'm done, this is plain delusion.

**Comment by Papa2Cherries** [comment]
Why would you even introduce the idea of "fixing" a non broken mechanic like crestfall's elegant way to tackle the issue.  Blizzlike means blizzlike.  Not, hey, something something economy sky is falling crap.  There is NO need to alter anything that has since been deemed blizzlike.  how does the tribute work.  you kill the king, and any remaining captains ALIVE give tribute to the new king...PERIOD.  How does one make certain the first two bosses are alive to give them tribute...BY getting past them and NOT KILLING THEM...PERIOD.  There should not be any "extra sauce" to make tribute runs non blizzlike, like the crestfall elegant solution.   IF they are alive, they give tribute.  So if you can find a way, ANY WAY, to kill the end boss without killing the guards, then they give tribute.....P E R I O D!!!

There should NOT be a mechanic introduced to make captains "seem" dead when they are not.  They patrol, they can be kyted out, they can be avoided, etc, those are all ways to KEEP THEM ALIVE for tribute.  Don't even give the crybabies another thought on how to alter it so we can artificially balance the economy.  So many people shout ECONOMY when dealing with valid blizzlike ways to make gold.  So sorry someone found a way to make gold you are not willing to do.  weather blizzard intended this, or just didn't think about it before it was out, matters not, we cannot know this.  We only know what was allowed and what was not.  and vanilla allowed mages to aoe farm the crap out of the world, and plate/healers to farm the crap out of dm E, and hunters to farm the crap out of DM N.  Stop the bitching about economy, gold per hour, not fair bullshit.  Just play the cards YOU are willing to play, and let the rest play what they are willing to play.

**Comment by staplerx300** [comment]
Bump

**Comment by adimeus** [comment]
If I'm not mistaken there is also a lasher drop rate nerf. Is that blizzlike and if not, is it reverted?

**Comment by VeryRare** [comment]
Bump - any comment from Dev or QA here? Been a while now and the code is ready to deploy

**Comment by brotalnia** [comment]
The required change to the code was made and was committed to the repository, there's nothing more to do. If you mean you want to see it pushed to the Light's Hope live realms, that depends solely on @thepparker.

**Comment by VeryRare** [comment]
Yes, I saw your code change - thanks. I'm bumping because we havn't received any official word back on this and wondering why @thepparker hasn't implemented it in release or commented as to why they won't be.

**Comment by Manlet** [comment]
For those interested, I open a topic in the suggestions section of the Light's Hope forum: https://forum.lightshope.org/viewtopic.php?f=6&t=9150

The earning potential for soloing tribute as a hunter is more than I originally thought, currently it is around 200G an hour solo, in the safety of an instance.

This would not be healthy for the server.

**Comment by LakeshireW** [comment]
who said this server will be a 100% blizzlike server?
there are lots of changes in this server that are not blizzlike, where is your comment on them?
Oh,making tons of gold is not what im gonna do! I just wanna solo tribute with the pride deep inside our hunter's heart!
Do you really think your filthy purpose can be hidden behind your selfish disguise? do both the server and other players a favor,delete your character and never come back again,k3 awaits u.

**Comment by brotalnia** [comment]
Closing this as the incorrect functionality in the emulator has been resolved, please take private server discussions to the forums.

**Comment by Papa2Cherries** [comment]
Now that ^^^ is a smackdown.  Great job Bro, tired of the "but i don't want it this way..." bs.
