### ISSUE TITLE
[custom change] 25 gold respec cost cap instead of 50 gold

### ISSUE THREAD

**Issue by AliUDmov** [LightsHope/server#956]
This custom change has been implemented a short time [after this announcement](https://forum.elysium-project.org/topic/48231-upcoming-pvp-update/) on June 6th.
> Respec costs are being lowered from a maximum of 50 gold to 25 gold.
The decay has not been changed.

The blizzlike version of this game mechanic [can be found here](http://wowwiki.wikia.com/wiki/Talent_build#Re-spec).
> Changing a character's talent build is called respeccing or is referred to as a respec. Characters can unlearn all of their talents (becoming untalented) at their respective class trainers, at a cost. Unlearning talents scales up the more times it is done: 1 gold, 5 gold, 10 gold, 15 gold, etc., up to 50 gold.
> The cost to unlearn talents decays over time. This cost will be reduced by a rate of 5 gold per month to a minimum of 10 gold.

There [had been numerous dicussions](http://forum.nostalrius.org/viewtopic.php?f=6&t=51) about the pro and contra arguments of this custom change and these discussions did not come to a final conclusion that pleases everyone. It would not hurt though, to evaluate this custom change and it's impact or demand after the already 5-6 months of active implementation. I suggest to revert this custom change for the sake of being blizzlike and true to the original game.

[To quote Viper from Nostalrius](http://forum.nostalrius.org/viewtopic.php?f=6&t=51&start=50#p677): 
> Respecialization cost cap will be as it was on retail.
> Not doing so will not be in line with Vanilla philosophy : diversity & difficulty.

**Comment by brotalnia** [comment]
This is a config setting and the default value is 50 gold. You can change it by opening _mangosd.conf_ in notepad.

https://github.com/LightsHope/server/blob/development/src/mangosd/mangosd.conf.dist.in#L1412

**Comment by AliUDmov** [comment]
Thank you for the clarification!

**Comment by Manlet** [comment]
IMO this has been nothing but positive for the server.

Many people I know have experimented more with different specs, or got more involved with PVP between raids, because it would no longer cost them 100g per week. 50g to respec pvp and back to pve for raid each week is still not cheap to most players, much more accessible than 100g.

The change in price hasn't been exactly life changing though, earlier updated PVP gear would have done a much better job.

**Comment by bigfgeg** [comment]
This was a conscious change made by the devs to keep people pvping. Reverting it would mean reverting the positive effects this has had on the battleground scene.

**Comment by Nyatsuelysium** [comment]
Queues are already insanely high considering a 10k pop.. 15 min just to get in a bg is messed up

**Comment by thepparker** [comment]
While this is a custom feature of our servers, it is something that we chose to do in order to encourage PvP activity. We do not believe it has a significant impact on gameplay, but instead allows players to experience different aspects of the game. Having a 50g respec cost does not add difficulty to the game, only an additional and, in our opinion, unnecessary gold sink.
